### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by bhavika** [bhavikat/URLExpander#1]
To do:

1) Handle error codes
2) DRY
3) Catch exceptions for when Location is empty

**Comment by geekyrudh** [comment]
#### WRT item 2 in the TODO:
Lines 26, 27 are the same as lines 43, 44.

**Comment by bhavikat** [comment]
Hey, you're right. That's why I put item 2 in the to do list. If you want to refactor that bit and send me a pull request, I'll merge it. Thanks!
